name: Build and Deploy

on:
  push:
    branches: 
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Create GH Pages
      run: |
        git remote set-url origin https://migueldlr:$TOKEN@github.com/migueldlr/visualization-tool.git # FIX THIS
        git config --global user.email "thisiswhataninjalookslike@gmail.com" # FIX THIS
        git config --global user.name "migueldlr" # FIX THIS
        npm ci
        npm run deploy
      env:
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
        USERNAME: migueldlr # FIX THIS
